### PR TITLE
Add `rustc-dev-guide` entry

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by crlf0710** [comment]
@JohnTitor Ping from triaging. could you address the comments above? Thanks.

**Comment by JohnTitor** [comment]
@crlf0710 Hm, transition is going on?

**Comment by crlf0710** [comment]
Seems rust-lang/rust#69898 is blocked on this. So maybe `rustc-dev-guide` item needs to be added first, then remove `rustc-guide` item in next PR after rust-lang/rust#69898 is merged ? Not sure if i understood it correctly. @JohnTitor

**Comment by JohnTitor** [comment]
@crlf0710 This PR and that rust-lang/rust PR are the remaining things of renaming rustc-guide to rustc-dev-guide (see tracking issue: rust-lang/rustc-dev-guide#602) and currently we're blocked since the transition should be done at once (also it'll affect other PRs on rust-lang/rust iirc so we should do carefully). I'll update this PR once we (wg-learning and infra folks) are ready but I think now is not the time. See the tracking issue or Zulip stream of wg-learning.

**Comment by spastorino** [comment]
> Please keep the `rustc-guide` entry until [rust-lang/rust#69898](https://github.com/rust-lang/rust/pull/69898) is merged (i.e. there should be both `rustc-guide` and `rustc-dev-guide` entries at the moment).
> 
> It is fine as long the `latest.json` is a superset of the result recorded in the `history/*.tsv` files.
> 
> Rest LGTM.

@JohnTitor I think you should address @kennytm comments in order to proceed with both things.

**Comment by JohnTitor** [comment]
Heh, I missed that, will follow-up later.

**Comment by JohnTitor** [comment]
Okay, added `rustc-dev-guide` entry.

**Comment by mark-i-m** [comment]
Yay! Our toolstate will work again :tada:

**Comment by Xanewok** [comment]
I (think) I'm hitting this at https://github.com/rust-lang/rust/pull/70149#issuecomment-609060927 with `mingw-check` when trying to upgrade RLS and Rustfmt.

Could you please take a look and help me unblock the work on this?

**Pull request merged**
